name: Release

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
  workflow_dispatch:

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for trusted publishing and npm provenance

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'

      - uses: pnpm/action-setup@v4

      - name: Cache ip2region data
        uses: actions/cache@v5
        with:
          path: packages/ts-ip2region2-data/data/
          key: ip2region-data-${{ hashFiles('packages/ts-ip2region2-data/data/checksums.json') }}
          restore-keys: |
            ip2region-data-

      - name: Install dependencies
        run: |
          pnpm install --ignore-scripts
          find node_modules -name "7za" -type f -exec chmod +x {} \;

      - name: Prepare ip2region2 Data
        run: |
          cd packages/ts-ip2region2-data
          pnpm build

          if [ ! -f "data/ip2region.7z" ]; then
            pnpm run sync
          fi

          node scripts/extract.js
      - name: Dry Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run semantic-release:dry

      - name: Run tests
        run: pnpm run test

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Release
        run: pnpm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
